In [2]:
import pandas as pd

In [9]:
df_sig = pd.read_csv(r"C:\Users\rudkevich-k\Desktop\patent_diploma\tests_searching\test_value\significat_test_result_claims.csv", index_col = 0)

In [29]:
df_sig = pd.read_csv(r"C:\Users\rudkevich-k\Desktop\patent_diploma\tests_searching\test_value\significat_test_result_bge_description.csv", index_col = 0)

In [19]:
df_pvalue

,Metric,name_exp,p-value
0,recall@5,result_description_delta_alpha_five.csv,0.000000e+00
1,precision@5,result_description_delta_alpha_five.csv,0.000000e+00
2,average_precision@5,result_description_delta_alpha_five.csv,0.000000e+00
3,mrr@5,result_description_delta_alpha_five.csv,0.000000e+00
4,recall@10,result_description_delta_alpha_five.csv,0.000000e+00
...,...,...,...
123,mrr@20,result_description_delta_alpha_two.csv,1.179125e-189
124,recall@30,result_description_delta_alpha_two.csv,1.349826e-250
125,precision@30,result_description_delta_alpha_two.csv,7.592321e-271
126,average_precision@30,result_description_delta_alpha_two.csv,2.260860e-275
127,mrr@30,result_description_delta_alpha_two.csv,6.307244e-191

In [22]:
df_pvalue[df_pvalue["p-value"]> 0.05]

Empty DataFrame
Columns: [Metric, name_exp, p-value]
Index: []

In [10]:
df_sig[df_sig['Significant'] == "❌ No"]

                   Metric                           name_exp Significant
144              recall@5  result_claims_delta_alpha_one.csv        ❌ No
145           precision@5  result_claims_delta_alpha_one.csv        ❌ No
146   average_precision@5  result_claims_delta_alpha_one.csv        ❌ No
147                 mrr@5  result_claims_delta_alpha_one.csv        ❌ No
148             recall@10  result_claims_delta_alpha_one.csv        ❌ No
149          precision@10  result_claims_delta_alpha_one.csv        ❌ No
150  average_precision@10  result_claims_delta_alpha_one.csv        ❌ No
151                mrr@10  result_claims_delta_alpha_one.csv        ❌ No
154  average_precision@20  result_claims_delta_alpha_one.csv        ❌ No
155                mrr@20  result_claims_delta_alpha_one.csv        ❌ No
156             recall@30  result_claims_delta_alpha_one.csv        ❌ No
157          precision@30  result_claims_delta_alpha_one.csv        ❌ No
158  average_precision@30  result_claims_delta_alpha_one.csv        ❌ No
159                mrr@30  result_claims_delta_alpha_one.csv        ❌ No
194   average_precision@5         result_claims_mlp_gelu.csv        ❌ No

In [15]:

df_base = pd.read_csv(r"C:\Users\rudkevich-k\Desktop\patent_diploma\tests_searching\result\result_claims_baseline.csv")
df_test = pd.read_csv(r"C:\Users\rudkevich-k\Desktop\patent_diploma\tests_searching\result\result_claims_delta_alpha_minus_three.csv")

Unnamed: 0              18774.500000
recall@5                    0.223186
precision@5                 0.077337
average_precision@5         0.149640
mrr@5                       0.223031
recall@10                   0.286975
precision@10                0.051795
average_precision@10        0.161409
mrr@10                      0.233761
recall@20                   0.353536
precision@20                0.032767
average_precision@20        0.167904
mrr@20                      0.239170
recall@30                   0.392907
precision@30                0.024590
average_precision@30        0.170225
mrr@30                      0.240952
dtype: float64

In [19]:
df_test.mean()

Unnamed: 0              1274.500000
recall@5                   0.256830
precision@5                0.101412
average_precision@5        0.180296
mrr@5                      0.288719
recall@10                  0.329392
precision@10               0.066275
average_precision@10       0.194215
mrr@10                     0.300240
recall@20                  0.394399
precision@20               0.039882
average_precision@20       0.200823
mrr@20                     0.305305
recall@30                  0.437993
precision@30               0.029712
average_precision@30       0.203539
mrr@30                     0.307093
dtype: float64

In [29]:
len(df_test["mrr@5"].dropna().tolist())

2550

In [34]:
import os

path = r"C:\Users\rudkevich-k\Desktop\patent_diploma\tests_searching\result"
    
for name in os.listdir(path):

    df_test = pd.read_csv(rf"{path}\{name}", index_col = 0)

    print(name, len(df_test))

result_claims_baseline.csv 37550
result_claims_delta_alpha_minus_five.csv 37550
result_claims_delta_alpha_minus_one.csv 37550
result_claims_delta_alpha_minus_three.csv 2550
result_claims_delta_alpha_minus_two.csv 37550
result_claims_delta_alpha_one.csv 37550
result_claims_delta_alpha_three.csv 37550
result_claims_delta_alpha_two.csv 37550
result_description_baseline.csv 37550
result_description_delta_alpha_minus_five.csv 75100
result_description_delta_alpha_minus_one.csv 75100
result_description_delta_alpha_minus_three.csv 5100
result_description_delta_alpha_minus_two.csv 75100
result_description_delta_alpha_one.csv 75100
result_description_delta_alpha_three.csv 75100
result_description_delta_alpha_two.csv 75100

In [ ]:
df_base['query_id'] = df_base.index
df_test['query_id'] = df_test.index

from scipy import stats
t_stat, p_value = stats.ttest_rel(df_base["mrr@5"].dropna().tolist(), df_test["mrr@5"].dropna().tolist())

ValueError: Array shapes are incompatible for broadcasting.

In [25]:
df_base["mrr@5"].dropna().tolist()

[1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.3333333333333333,
 0.0,
 1.0,
 0.0,
 0.2,
 0.0,
 0.5,
 0.0,
 0.5,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.3333333333333333,
 0.0,
 0.0,
 0.0,
 1.0,
 0.5,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.5,
 0.0,
 1.0,
 0.0,
 0.2,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.2,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.3333333333333333,
 1.0,
 0.0,
 0.2,
 1.0,
 0.0,
 1.0,
 1.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.3333333333333333,
 0.0,
 1.0,
 0.0,
 1.0,
 0.5,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.5,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.5,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.5,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.2,
 0.0,
 0.2,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.3333333333333333,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.5,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 0.3333333333333333,
 0.0,
 0.5,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.3333333333333333,
 0.3333333333333333,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.5,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.3333333333333333,
 0.0,
 1.0,
 0.0,
 0.0,
 0.2,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.25,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.5,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.5,
 0.0,
 1.0,
 1.0,
 0.5,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.5,
 1.0,
 0.5,
 0.2,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.5,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.2,
 1.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.2,
 0.0,
 0.25,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.2,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.2,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.5,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.25,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.2,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.2,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.3333333333333333,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.5,
 1.0,
 0.0,
 0.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.2,
 1.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.5,
 0.3333333333333333,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.3333333333333333,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.3333333333333333,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.3333333333333333,
 0.25,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.5,
 0.3333333333333333,
 0.0,
 0.3333333333333333,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.25,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.0,
 0.5,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.3333333333333333,
 0.5,
 0.0,
 1.0,
 0.5,
 1.0,
 0.0,
 0.2,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.3333333333333333,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.3333333333333333,
 0.3333333333333333,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.2,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.2,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.2,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.2,
 0.3333333333333333,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.5,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.0,
 1.0,
 0.0,
 0.0,
 0.25,
 0.0,
 1.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.5,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 1.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.5,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.3333333333333333,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.5,
 0.0,
 1.0,
 0.25,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.3333333333333333,
 0.3333333333333333,
 0.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 0.5,
 1.0,
 1.0,
 0.3333333333333333,
 0.25,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.3333333333333333,
 0.0,
 0.0,
 0.3333333333333333,
 0.0,
 0.2,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.3333333333333333,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.2,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.2,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.25,
 0.3333333333333333,
 0.0,
 0.0,
 1.0,
 1.0,
 0.25,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.5,
 0.3333333333333333,
 0.0,
 0.0,
 1.0,
 1.0,
 0.3333333333333333,
 0.5,
 1.0,
 0.3333333333333333,
 ...]

<bound method DataFrame.value_counts of        Unnamed: 0  recall@5  precision@5  average_precision@5  mrr@5  \
0           False     False        False                False  False
1           False     False        False                False  False
2           False     False        False                False  False
3           False     False        False                False  False
4           False     False        False                False  False
...           ...       ...          ...                  ...    ...
37545       False     False        False                False  False
37546       False     False        False                False  False
37547       False     False        False                False  False
37548       False     False        False                False  False
37549       False     False        False                False  False

       recall@10  precision@10  average_precision@10  mrr@10  recall@20  \
0          False         False                 False   False      False
1          False         False                 False   False      False
2          False         False                 False   False      False
3          False         False                 False   False      False
4          False         False                 False   False      False
...          ...           ...                   ...     ...        ...
37545      False         False                 False   False      False
37546      False         False                 False   False      False
37547      False         False                 False   False      False
37548      False         False                 False   False      False
37549      False         False                 False   False      False

       precision@20  average_precision@20  mrr@20  recall@30  precision@30  \
0             False                 False   False      False         False
1             False                 False   False      False         False
2             False                 False   False      False         False
3             False                 False   False      False         False
4             False                 False   False      False         False
...             ...                   ...     ...        ...           ...
37545         False                 False   False      False         False
37546         False                 False   False      False         False
37547         False                 False   False      False         False
37548         False                 False   False      False         False
37549         False                 False   False      False         False

       average_precision@30  mrr@30
0                     False   False
1                     False   False
2                     False   False
3                     False   False
4                     False   False
...                     ...     ...
37545                 False   False
37546                 False   False
37547                 False   False
37548                 False   False
37549                 False   False

[37550 rows x 17 columns]>